### ISSUE TITLE
Korean Content

### ISSUE THREAD

**Issue by AdrienFromToulouse** [philsturgeon/protect.earth#10]
Translate content to Korean.

What content should be prioritised?

TODO:
- [ ] check KR country flag exists in assets
- [ ] check country selector in UI
- [ ] check font
- [ ] provide a way to submit translation

**Comment by philsturgeon** [comment]
We actually have a plan! Let's focus on finding actions for folks living in South Korea, and any other countries you have information on, and we'll sort out localization after the rewrite to Statamic. https://github.com/philsturgeon/protect.earth/issues/14
